### ISSUE TITLE
Hi, I'm Chasing

### ISSUE THREAD

**Issue by Chasing1020** [Chasing1020/Chasing1020.github.io#1]
This blog is established by hugo which is a static site engine written in Go.
To achieve faster access, I have rebuilt this blog by it in replacing of hexo.
The frequency of updating this blog is unknown, depending on the state of my recent studies.

I would appreciate it if you could add my blog to your links.

You can send me your link by any means, an example of the link is below.
```yaml
name: "Chasing"
url: "https://chasing1020.github.io"
avatar: "https://avatars.githubusercontent.com/chasing1020"
description: "Why there is a universe?"
```
